name: Update blog posts

on:
  schedule:
  - cron: "0 0 * * 0"
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://cheeaun.com/blog/feed.xml'
          file: 'README.md'
      - uses: sarisia/actions-commit@master
